#using variables for src and dest is probably a good thing
- name: push daq  source files
  become: yes
  copy: src=libdaq.v3.0.9.tar.gz dest={{ remote_install_path }}
  register: daq_source
 
- name: push snort source files
  become: yes
  copy: src=snort.3.1.36.0.tar.gz dest={{ remote_install_path }}
  register: snort_source

#installing dependencies
- name: installing dependencies
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}" 
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - dh-autoreconf
    - pkg-config
    - libmnl-dev
    - cmake
    - bison
    - flex
    - libpcap-dev
    - libdnet-dev
    - libdumbnet-dev
    - libhwloc-dev
    - libpcre3-dev
    - libluajit-5.1-dev
    - libssl-dev
    - zlib1g-dev
    - liblzma-dev
    - openssl
    - libnetfilter-queue-dev
    - iptables-persistent
#unpacking daq
- name: unpacking daq
  become: yes
  ansible.builtin.unarchive:
    copy: no
    dest: /opt/
    src: "{{ remote_install_path_daq }}"
  when: daq_source is succeeded
  register: daq_source_unpacked
  
#Configuring daq
- name: configuring daq
  become: yes
  ansible.builtin.shell: ./bootstrap && ./configure 
  args:
    chdir: /opt/libdaq-3.0.9
  when: daq_source_unpacked is succeeded
  register: daq_configure

#Installing daq
- name: Installing daq
  become: yes
  ansible.builtin.shell: make && make install
  args:
    chdir: /opt/libdaq-3.0.9
  when: daq_configure is succeeded
  register: daq_installed

#unpacking snort
- name: unpacking snort 
  become: yes
  ansible.builtin.unarchive:
    copy: no
    dest: /opt/
    src: "{{ remote_install_path_snort }}"
  when: snort_source is succeeded
  register: snort_source_unpacked

#configuring snort
- name: Configuring snort
  become: yes
  ansible.builtin.command: "./configure_cmake.sh"
  args:
    chdir: /opt/snort3-3.1.36.0
  when: snort_source_unpacked is succeeded
  register: snort_configured


#installing snort
- name: Installing snort
  become: yes
  ansible.builtin.shell: make && make install
  args:
    chdir: /opt/snort3-3.1.36.0/build
  when: snort_configured is succeeded 
  register: snort_installed

- name: Configure Dynamic Linker
  become: yes
  ansible.builtin.command: "ldconfig"
  when: snort_installed is succeeded

#create symlink to use for a systemd unit later on
- name: Creating Symlink
  become: yes
  ansible.builtin.file:
    src: "/usr/local/snort/bin/snort"
    dest: "/usr/sbin/snort"
    state: link
    
#Copying template config file


- name: Copying template of config file
  become: yes
  ansible.builtin.template: 
    src: "snort.lua.j2"
    dest: "/usr/local/snort/etc/snort/snort.lua"
  when: snort_installed is succeeded
  register: snort_lua_created
#create snort user and group

- name: creating snort group
  become: yes 
  group:
    name: snort
  register: snort_group_created

- name: creating snort user 
  become: yes
  user:
    name: snort
    system: yes
    shell: /sbin/nologin
    create_home: no
    comment: SNORT IPS
    group: snort
  when: snort_group_created is succeeded
  register: snort_user_created

#Create Log directory

- name: creating log directory 
  become: yes
  ansible.builtin.file:
    path:  /var/log/snort/
    state: directory
    owner: snort
    group: snort
    recurse: yes
    mode:  5755
  when: (snort_group_created is succeeded) and (snort_user_created is succeeded)

#Setting systemd unit

- name: Copying snort service unit file
  become: yes
  ansible.builtin.copy:
    src: snort3.service
    dest: /lib/systemd/system/snort3.service
  when: snort_installed is succeeded
  register: snort_unit_created

#Daemon reload

- name: Restarting Systemd daemon and enabling snort
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: snort.service
    state: started
  register: snort_service_started
  
#Configuring Iptables

- name: iptables input   and output rule
  become: yes
  ansible.builtin.shell: "iptables -F && iptables -A OUTPUT -j NFQUEUE --queue-num 0 --queue-bypass && iptables -A INPUT -j NFQUEUE --queue-num 0 --queue-bypass"
  when: snort_service_started is succeeded
  notify: save iptables

