# Pushin tar archive containing rules to remote hosts


- name: push tar containing rules
  become: yes
  copy: 
    src: "snortrules-snapshot-31350.tar.gz"
    dest: "{{ SNORT_RULE_PATH }}/snort_rules/"
  register: rules_pushed


#untar rules

- name: untar snort rules
  become: yes
  ansible.builtin.unarchive: 
    src: "{{SNORT_RULE_PATH}}/snort_rules/snortrules-snapshot-31350.tar.gz"
    dest: "{{ SNORT_RULE_PATH }}/snort_rules/"
    remote_src: yes
  when: rules_pushed is succeeded
  register: rules_unpacked



#copy necessary files in their respective paths

- name: push rule files to remote host
  become: yes
  copy: 
    src: "{{ SNORT_RULE_PATH }}/snort_rules/{{ item }}/"
    dest: "{{ SNORT_PATH }}/etc/{{ item  }}/"
    remote_src: yes
  with_items: 
    - "builtins"
    - "rules"
    - "so_rules"
  when: rules_unpacked is succeeded
  register: rule_files_copied

#Include new rules in configuration file 

- name: include new rules
  become: yes
  ansible.builtin.blockinfile: 
    path: '{{ SNORT_PATH }}/etc/snort/snort.lua'
    marker: "-- {mark} ANSIBLE MANAGED BLOCK"
    block: |
        rules = [[

        include $RULE_PATH//snort3-app-detect.rules
        include $RULE_PATH//snort3-browser-chrome.rules
        include $RULE_PATH//snort3-browser-firefox.rules
        include $RULE_PATH//snort3-browser-ie.rules
        include $RULE_PATH//snort3-browser-other.rules
        include $RULE_PATH//snort3-browser-plugins.rules
        include $RULE_PATH//snort3-browser-webkit.rules
        include $RULE_PATH//snort3-content-replace.rules
        include $RULE_PATH//snort3-exploit-kit.rules
        include $RULE_PATH//snort3-file-executable.rules
        include $RULE_PATH//snort3-file-flash.rules
        include $RULE_PATH//snort3-file-identify.rules
        include $RULE_PATH//snort3-file-image.rules
        include $RULE_PATH//snort3-file-java.rules
        include $RULE_PATH//snort3-file-multimedia.rules
        include $RULE_PATH//snort3-file-office.rules
        include $RULE_PATH//snort3-file-other.rules
        include $RULE_PATH//snort3-file-pdf.rules
        include $RULE_PATH//snort3-indicator-compromise.rules
        include $RULE_PATH//snort3-indicator-obfuscation.rules
        include $RULE_PATH//snort3-indicator-scan.rules
        include $RULE_PATH//snort3-indicator-shellcode.rules
        include $RULE_PATH//snort3-malware-backdoor.rules
        include $RULE_PATH//snort3-malware-cnc.rules
        include $RULE_PATH//snort3-malware-other.rules
        include $RULE_PATH//snort3-malware-tools.rules
        include $RULE_PATH//snort3-netbios.rules
        include $RULE_PATH//snort3-os-linux.rules
        include $RULE_PATH//snort3-os-mobile.rules
        include $RULE_PATH//snort3-os-other.rules
        include $RULE_PATH//snort3-os-solaris.rules
        include $RULE_PATH//snort3-os-windows.rules
        include $RULE_PATH//snort3-policy-multimedia.rules
        include $RULE_PATH//snort3-policy-other.rules
        include $RULE_PATH//snort3-policy-social.rules
        include $RULE_PATH//snort3-policy-spam.rules
        include $RULE_PATH//snort3-protocol-dns.rules
        include $RULE_PATH//snort3-protocol-finger.rules
        include $RULE_PATH//snort3-protocol-ftp.rules
        include $RULE_PATH//snort3-protocol-icmp.rules
        include $RULE_PATH//snort3-protocol-imap.rules
        include $RULE_PATH//snort3-protocol-nntp.rules
        include $RULE_PATH//snort3-protocol-other.rules
        include $RULE_PATH//snort3-protocol-pop.rules
        include $RULE_PATH//snort3-protocol-rpc.rules
        include $RULE_PATH//snort3-protocol-scada.rules
        include $RULE_PATH//snort3-protocol-services.rules
        include $RULE_PATH//snort3-protocol-snmp.rules
        include $RULE_PATH//snort3-protocol-telnet.rules
        include $RULE_PATH//snort3-protocol-tftp.rules
        include $RULE_PATH//snort3-protocol-voip.rules
        include $RULE_PATH//snort3-pua-adware.rules
        include $RULE_PATH//snort3-pua-other.rules
        include $RULE_PATH//snort3-pua-p2p.rules
        include $RULE_PATH//snort3-pua-toolbars.rules
        include $RULE_PATH//snort3-server-apache.rules
        include $RULE_PATH//snort3-server-iis.rules
        include $RULE_PATH//snort3-server-mail.rules
        include $RULE_PATH//snort3-server-mssql.rules
        include $RULE_PATH//snort3-server-mysql.rules
        include $RULE_PATH//snort3-server-oracle.rules
        include $RULE_PATH//snort3-server-other.rules
        include $RULE_PATH//snort3-server-samba.rules
        include $RULE_PATH//snort3-server-webapp.rules
        include $RULE_PATH//snort3-sql.rules
        include $RULE_PATH//snort3-x11.rules

        ]],
    insertbefore: '-- use this to enable decoder'
  when: rule_files_copied is succeeded
  register: rules_included
  notify: restart snort
